### ISSUE TITLE
[RFC] preset-vue

### ISSUE THREAD

**Issue by xierenyuan** [umijs/umi-next#604]
# 背景
通过实现 `@umijs/preset-vue` 完成对vue 3 框架的支持(vue2 是否有必要支持)

# 想做的事情
除react 特有feature外, 可复用umi 目前所有能力. 如依赖预打包, 插件机制, mock, 运行时插件, mfsu, devTools, appData, check 等等.

# 详细设计

## @umijs/renderer-vue
- [ ] 支持vue 框架渲染, 暴露运行时配置 `rootContainer`, `accessProvider` 同 renderer-react 
- [ ] 新增vue 独有运行时配置

-    router 修改路由配置
-    onMounted 暴露 vue 示例 `app`, `router`  用于插件全局挂载vue 组件或者 路由拦截器等

- [ ] useAppData

实现 
```tsx
  let rootContainer = App;

  for (const key of [
    // Lowest to the highest priority
    'innerProvider',
    'accessProvider',
    'dataflowProvider',
    'rootContainer',
  ]) {
    rootContainer = opts.pluginManager.applyPlugins({
      type: 'modify',
      key,
      initialValue: rootContainer,
      args: {},
    });
  }

  // 路由配置
  const routerConfig = opts.pluginManager.applyPlugins({
    key: 'router',
    type: 'modify',
    initialValue: {},
  });

  const router = createRouter({
    ...routerConfig,
    history: opts.history,
    strict: true,
    routes,
  });

  opts.pluginManager.applyPlugins({
    type: 'event',
    key: 'onRouterCreated',
    args: {
      router,
    },
  });

  const app = createApp(rootContainer);

  opts.pluginManager.applyPlugins({
    type: 'event',
    key: 'onAppCreated',
    args: {
      app,
    },
  });

  // 注入appData 数据
  app.provide(AppContextKey, {
    routes: opts.routes,
    routeComponents: opts.routeComponents,
    clientRoutes: routes,
    pluginManager: opts.pluginManager,
    rootElement: opts.rootElement,
  });

  app.use(router);

  app.mount(opts.rootElement);

  opts.pluginManager.applyPlugins({
    type: 'event',
    key: 'onMounted',
    args: {
      app,
      router,
    },
  });
```

使用
```ts
// app.tsx
import { RouterConfig } from 'umi';

export function onRouterCreated({ router }: any) {
  console.log('onRouterCreated', router);
}

export function onAppCreated({ app }: any) {
  console.log('onAppCreated', app);
}

export function onMounted({ app, router }: any) {
  console.log('onMounted', app, router);
}

export const router: RouterConfig = {
  scrollBehavior(to, from) {
    console.log('scrollBehavior', to, from);
  },
};

```

## @umijs/preset-vue

- [ ] vue 相关webpack 配置
- [ ] mfsu vue 相关webpack 配置
- [ ] vite 相关配置
- [ ] 文件生成相关覆盖涉及到 history, EmptyRoutes.vue
- [ ] 渲染器修改 babel 配置修改

## @umijs/babel-preset-vue
> 看是否要跟umi 的babel 配置合并

- [ ] tsx 支持
- [ ] vue 支持

实现关键改动点
```tsx
presets: [
  [
      require.resolve('@umijs/bundler-utils/compiled/babel/preset-typescript'),
      {
        // 支持vue 后缀
        allExtensions: true,
        // 支持tsx
        isTSX: true,
        allowNamespaces: true,
        allowDeclareFields: true,
        onlyRemoveTypeImports: true,
        optimizeConstEnums: true,
        ...opts.presetTypeScript,
      },
    ],
]
plugins: [
    // jsx
    [require.resolve('@vue/babel-plugin-jsx')],
]
```

### preset-umi

* 针对vue 相关的一些改动点兼容, 看是否能在 preset-vue 覆盖

### bundler-vite

* 对react 插件增加一个开关 vue 模式关闭

### 插件

- [ ] request 兼容vue 还是直接新开一个插件 主要涉及到 @ahooksjs/use-request
- [ ] initial-state
- [ ] model
- [ ] access
- [ ] pinia(vue状态库)
- [ ] elementplus(vue 组件库)

### 提供开箱即用的模板

create-umi 新增vue 模板

## TODO

有些能力 实现时需要考虑vue 版本 如ssr 之类的 还是先不支持 慢慢迭代
