### ISSUE TITLE
`plugin-docs` 文档插件 TODO

### ISSUE THREAD

**Issue by ken20001207** [umijs/umi-next#714]
- [ ] 标题的锚点按钮
- [ ] "上一篇" / "下一篇" 文档链接
- [ ] 文档上次更新时间
- [ ] 文档编辑链接（快速跳转到 GitHub 仓库对应文件的链接）
- [ ] 文档单代码块支持切换不同语言的实现 （类似 [esbuild 的文档](https://esbuild.github.io/api/#allow-overwrite)）
- [ ] 文档点赞功能（参考 [这个文档](https://www.joshwcomeau.com/javascript/terminal-for-js-devs/) 右下方的爱心，点击还有音效）
- [ ] 优化主题切换开关的呈现方式（参考 [这个文档](https://www.joshwcomeau.com/javascript/terminal-for-js-devs/) 右上方的太阳/月亮，点击还有音效）

**Comment by fz6m** [comment]
1. 滚动条优化下？
2. 右侧目录范围太窄了，扩大下或者不要外框全展示，会不会更好？
