### ISSUE TITLE
Umi 3 Progress

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi-next#9]
## The big picture

![image](https://user-images.githubusercontent.com/35128/71536973-990b5280-2950-11ea-9786-87156ce6a061.png)

## Milestone

* [x] 12.13 Initial the repo, including **Directory Structure**
* [x] 12.20 \@umijs/core, including **Plugin system** and **Config**
* [x] 12.27 \@umijs/runtime + \@umijs/renderer-react + File Generate
* [x] 01.10 \@umijs/routes + \@umijs/bundler
* [x] 01.17 Release umi@3-alpha
* [ ] 03.02 Release umi@3

## Packages

* [ ] core
  * [x] Service + PluginAPI
  * [x] Config
  * [x] Routes
  * [x] Html
  * [ ] Logger
* [x] preset-built-in
  * [x] generateFiles
  * [x] commands/buid
  * [x] commands/dev
* [ ] runtime
  * [x] Plugin
  * [ ] dynamic
* [ ] renderer-react
  * [x] renderClient
  * [x] renderRoutes
  * [ ] renderServer
* [ ] bundler
* [x] bundler-webpack
* [x] utils
* [x] test
* [x] babel-preset-umi
* [x] types
* [ ] ast

**Comment by sorrycc** [comment]
## Alpha Progress

* Chore
	* [x] 添加 babel-plugin-react-require
	* [x] 移动所有插件到 babel-preset-umi
	* [x] 内置 react 和 react-dom 的 alias
	* [x] 内置 react-router 相关仓库的 alias，不允许用户定制
	* 升级 babel 和 corejs 依赖
* Webpack
	* [x] targets 配置，串 js 和 css
	* [x] runtimePublicPath
	* [x] define 配置
	* [ ] build 的 watch mode
	* [ ] 改写 babel-plugin-react-require
	* [ ] 愚道的问题
* Dev
	* [ ] HMR
	* [ ] Proxy @ycjcl868 
	* [ ] Mock @ycjcl868 
	* [ ] 重启机制支持 bundle 重启
	* [ ] watch 机制
* 插件试验
	* [ ] 准备官方插件仓库
	* [ ] umi-plugin-react 下所有插件跑通
	* [ ] 最佳实践插件跑通
		* plugin-model
		* plugin-access
		* plugin-request
		* ...
	* [ ] qiankun 插件跑通
	* [ ] ant-design-pro 跑通
	* [ ] 脚手架里的 app 类型跑通
* [ ] 发布脚本
* [ ] 整理 umi 3 特性为文章

**Comment by ycjcl868** [comment]
Proxy 和 Mock 相关的 middleware 是写在 `@umijs/server` 还是 `preset-built-in` 中？

**Comment by kaoding** [comment]
期待 umi 3.0 发布
